---
title: "lecture"
output: github_document
date: "2022-09-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(nycflights13)
library(ggplot2)
library(sjmisc)
```

```{r}
# assignment1
ques1 = flights %>% 
  group_by(tailnum) %>% 
  summarise(missing_dep_time = sum(is.na(dep_time)), n = n()) %>% 
  arrange(desc(missing_dep_time))

ques1_b = ques1 %>% 
  filter(missing_dep_time == 1)

nrow(ques1)
nrow(ques1_b)

other = sapply(flights, function(x) sum(is.na(x)))
la = labels(other[other > 0])
la
```
those flights had been cancelled

```{r}
ques2 = flights %>% 
  mutate(dep_time = (dep_time %/% 100) * 60 + (dep_time %% 100), 
         sched_dep_time = (sched_dep_time %/% 100) * 60 + (sched_dep_time %% 100))
ques2
```

```{r}
#[1] "dep_time"  "dep_delay" "arr_time" 
#[4] "arr_delay" "tailnum"   "air_time" 

ques3 = flights %>% 
  mutate(cancel = (is.na(dep_time)) | (is.na(dep_delay)) | (is.na(arr_time)) | (is.na(arr_delay)) | (is.na(air_time))) %>% 
  group_by(day) %>% 
  summarise(po = mean(cancel), sum = sum(cancel), n = n()) %>%
  ggplot(aes(x = day)) +
    geom_point(aes(y = sum)) +
    geom_line(aes(y = po))
ques3
```

